version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    volumes:
      - 'enferno:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass verystrongpass
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    build: .
    env_file:
      - '.env'
    volumes:
      - '.:/enferno-plat'
    ports:
      - '8000:5000'

  celery:
    build: .
    command: celery worker -B -l info -A enferno.tasks
    env_file:
      - '.env'
    volumes:
      - '.:/enferno-plat'

volumes:
  enferno:
  redis:
