version: '3'

services:

  redis:
    container_name: redis 
    image: 'redis:7-alpine'
    command: redis-server --requirepass verystrongpassword
    volumes:
      - 'redis-data:/var/lib/redis/data'
    ports:
      - '6379:6379'

  website:
    container_name: website
    build: .
    env_file:
      - '.env'
    volumes:
      - 'enferno:/app'
    links:
      - redis
    ports:
      - '8000:5000'


  nginx:
    container_name: nginx
    restart: always
    image: 'bitnami/nginx:latest'
    ports:
      - '80:80'
    volumes:
      - './enferno/static/:/app/static/'
      - './nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf'
      - './nginx/enferno.conf:/opt/bitnami/nginx/conf/server_blocks/enferno.conf'
    depends_on:
      - website
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]

  celery:
    container_name: celery
    build: .
    command: celery -A enferno.tasks worker -l info 
    env_file:
      - '.env'
    links:
      - redis
    volumes_from:
      - website


volumes:
  enferno:
  redis-data:
  
